project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
  resources:
    - "class/"
    - "rubrics/"
    - "slides/"
    - "data/"

website:
  title: EMSE 6035
  image: images/logo.png
  site-url: https://madd.seas.gwu.edu/2023-Fall/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-madd-gwu/2023-Fall
  repo-actions: [edit, issue]
  description: 'Course website for Fall 2023 semester of the EMSE course "Marketing Analytics for Design Decisions" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://madd.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Syllabus
        icon: map-fill
        href: syllabus.qmd
      - text: Schedule
        icon: table
        href: schedule.qmd
      - text: Project
        icon: list-check
        href: project.qmd
      - section: Project
        icon: question-circle-fill
        contents:
          - text: Overview
            href: 0-overview.qmd
          - text: Proposal (Due Sep 25)
            href: 1-proposal.qmd
          - text: Survey Plan (Due Oct 04)
            href: 2-survey-plan.qmd
          - text: Pilot Survey (Due Oct 18)
            href: 3-pilot-survey.qmd
          - text: Pilot Analysis (Due Nov 06)
            href: 4-pilot-analysis.qmd
          - text: Final Survey (Due Nov 20)
            href: 5-final-survey.qmd
          - text: Final Analysis (Due Dec 11)
            href: 6-final-analysis.qmd
          - text: Final Presentation (On Dec 14)
            href: 7-final-presentation.qmd
          - text: Examples
            icon: file-earmark-medical
            href: help/example-projects.qmd
      - text: Getting Help
        icon: question-circle
        href: help/getting-help.qmd
      - text: References
        icon: bookmark-fill
        href: references.qmd
      - text: Slack
        icon: slack
        href: https://emse-madd-f23.slack.com
      - text: "Schedule a call w/Prof. Helveston"
        icon: clock-fill
        href: https://jhelvy.appointlet.com/b/professor-helveston
      - section: Other
        icon: question-circle-fill
        contents:
          - text: About
            icon: question-circle-fill
            href: about.qmd
          - text: License
            icon: award-fill
            href: LICENSE.qmd
          - text: Contact
            icon: envelope-fill
            href: mailto:jph@gwu.edu
          - text: Source files
            icon: github
            href: https://github.com/emse-madd-gwu/2023-Fall
  page-footer:
    center:
      - text: '© 2023 John Paul Helveston <a href="LICENSE.html"><i class="fab fa-creative-commons"></i><i class="fab fa-creative-commons-by"></i><i class="fab fa-creative-commons-sa"></i></a><br><i class="far fa-calendar-alt"></i> {{< var weekday >}} | <i class="far fa-clock"></i> {{< var time >}} | <a href="{{< var room_url >}}"><i class="fa fa-map-marker-alt"></i> {{< var room >}}</a> | <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> | <a href="mailto:{{< var email >}}"><i class="fas fa-envelope"></i> {{< var email >}}</a> | <a href="{{< var repo >}}"><i class="fab fa-github"></i></a>'

format:
  html:
    theme: cosmo
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false

filters:
    - schedule.lua
